// export const BASE_URL = process.env.BASE_URL;
export const VAPID_KEY = process.env.VAPID_KEY
export const apiKey = process.env.apiKey
export const authDomain = process.env.authDomain
export const projectId = process.env.projectId
export const storageBucket = process.env.storageBucket
export const messagingSenderId = process.env.messagingSenderId
export const appId = process.env.appId
export const measurementId = process.env.measurementId